name: RL DevOps Tool Suite
version: 0.1
rundeckPluginVersion: 1.1
author: chuck.hilyard@reachlocal.com
date: 8/19/2016
providers:
    - name: RL DevOps Tool Suite
      service: WorkflowNodeStep
      plugin-type: script
      script-interpreter: /usr/bin/env ruby
      script-file: runtime.rb
      script-args: arg1 arg2 arg3 arg4 arg5 arg6 arg7 arg8 arg9 arg10
