name: RL DevOps Tools
version: 0.1
rundeckPluginVersion: 1.1
author: chuck.hilyard@reachlocal.com
date: 8/19/2016
providers:
    - name: QA Mutable Environment Switch
      service: WorkflowStep
      plugin-type: script
      script-interpreter: /usr/bin/env ruby
      script-file: runtime.rb
      script-args: mutable environment
