name: JIRA Ticket Check
version: 0.1
rundeckPluginVersion: 1.1
author: chuck.hilyard@reachlocal.com
date: 8/19/2016
providers:
    - name: JIRA Ticket Check
      service: WorkflowNodeStep
      plugin-type: script
      script-interpreter: /usr/bin/env ruby
      script-file: runtimehandler.rb
      script-args: jira check 
