#!/bin/bash
# 
# this is a front-end to pass variables to Ruby from the command line

cliargs()
{
    echo -e "$0\t[ jira TICKETNUMBER ]" 
    echo -e "\t\t[ netscaler basiclb ]"
}

export RD_OPTION_TICKETNUMBER="cmr-1255"
#export RD_OPTION_TICKETNUMBER="disp-9999"
export RD_JOB_USERNAME="chuck.hilyard"
export RD_JOB_ID="e57499ca-a118-4280-9095-802046417263"
export RD_JOB_URL="http://rundeck-usa-app01.dev.wh.reachlocal.com:4440/project/Pre-Production/execution/follow/14"

case $1 in
        jira) /usr/bin/env ruby $1 $2;;
   netscaler) /usr/bin/env ruby $1 $2;;
           *) cliargs;;
esac

