#!/bin/bash
# 
# this is a cli front-end to mock the rundeck frontend.

# plugins have a plugin.yaml file, this is how rundeck will interface w/ your plugin
# it'll look something like this

cliusage()
{
    echo -e "* parameters are positional"
    echo -e "*\t\tKEY     \t ACTION           \t VALUES"
    echo -e "$0\t\t[ jira ] \t [ create ]       \t [ type ] [ assignee ] [ note ]" 
    echo -e "\t\t         \t [ check ]        \t [ ticketnumber ]" 
    echo -e "\t\t[ lb   ] \t [ add|remove ]   \t [ dev|qa|stg|prod ] [ netscaler|elb ] [ basiclb|switchinglb ] [ usa|can|eur|gbr|jpn|aus ]" 
    echo -e "\t\t         \t [ passwd ]       \t   changes your password on all netscaler lb's { wh,lax,iad,syd,nrt,ams } " 
    echo -e "\t\t[ node ] \t [ add|remove ]   \t [ dev|qa|stg|prod ] [ ec2|xen|rlpc ] [ web|app|admin|db ] [ usa|can|eur|gbr|jpn|aus ]" 
    echo -e "\t\t[ mutable ]   \t [ qa_nx1|qa_cur ] \t [ int1|int2 ] to [ can|eur|gbr|jpn|aus ]"
}


# this script should only be run from the top level directory as this is 
# where rundeck will interface w/ the plugin
if [ "$PWD" != "/Users/chuck.hilyard/projects/rlrundeck-plugin/contents" ]
    then
        echo "run this from /Users/chuck.hilyard/projects/rlrundeck-plugin/contents, only"
        exit

    else
       :
fi

## RD_OPTION vars are built at rundeck execution time and maintained in the rundeck session
#export RD_OPTION_TICKETNUMBER="cmr-1255"
#export RD_OPTION_TICKETNUMBER="disp-9999"
#export RD_JOB_USERNAME="chuck.hilyard"
#export RD_JOB_ID="e57499ca-a118-4280-9095-802046417263"
#export RD_JOB_URL="http://rundeck-usa-app01.dev.wh.reachlocal.com:4440/project/Pre-Production/execution/follow/14"
#export JOB_SOURCE="devopscli"
export RD_OPTION_ENVIRONMENT="qa_nx1"
export RD_OPTION_RUNWAY="int1"
export RD_OPTION_PLATFORM="can"

if [ "$*" ]
    then 
        /usr/bin/env ruby runtimehandler.rb $@

    else
        cliusage
    fi

