name: AWS ELB REST Handler
version: 0.1
rundeckPluginVersion: 1.1
author: chuck.hilyard@reachlocal.com
date: 8/19/2016
providers:
    - name: Netscaler REST Handler
      service: WorkflowNodeStep
      plugin-type: script
      script-interpreter: /usr/bin/env ruby
      script-file: resthandler.rb
      script-args: arg1 arg2
